 Python environment olarak Google Colab kullanacağım bunun nedeni hem web tabanlı olması hem de neredeyse tam kontrole izin vermesi, ayrıca sağladığı drive araçları sayesinde verileri buluttan güncel olarak çekerek, projeleri hem daha güncel hem de daha hızlı çalışacak şekilde tutması. Ham verimizi Colab ortamına yüklemek için gerekli kod betiklerini aşağıda yazdım.

In [5]:
import pandas as pd

In [2]:
df = pd.read_csv('/eco_driving_score (1).csv')
display(df.head())

,rpm_variation,harsh_braking_count,idling_time,fuel_consumption,acceleration_smoothness,eco_score
0,2147,5,14.2,7.87,0.97,42.1
1,1703,3,4.2,9.37,0.50,36.1
2,2253,0,5.5,8.85,0.78,49.8
3,2866,3,21.7,5.87,0.60,27.7
4,1636,2,3.1,6.71,0.99,79.4

Öncelikle ham verimiz Üzerinde EDA yapacağız, Bu aşamada verimizin satır, sütun sayılarını, sütun tiplerini, veri tiplerini incelemek için Pandas kütüphanesinin metodlarından faydalandım.

In [3]:
# Veri setinin boyutunu (satır ve sütun sayısı) yazdırıyoruz
print(f"Veri Seti Boyutu: {df.shape[0]} satır, {df.shape[1]} kolon\n")

# Sütunların veri tiplerini ve eksik (null) değer sayısını gösteriyoruz
print("VERİ TİPLERİ VE EKSİK DEĞER KONTROLÜ:")
df.info()

Veri Seti Boyutu: 30000 satır, 6 kolon

VERİ TİPLERİ VE EKSİK DEĞER KONTROLÜ:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rpm_variation            30000 non-null  int64
 1   harsh_braking_count      30000 non-null  int64
 2   idling_time              30000 non-null  float64
 3   fuel_consumption         30000 non-null  float64
 4   acceleration_smoothness  30000 non-null  float64
 5   eco_score                30000 non-null  float64
dtypes: float64(4), int64(2)
memory usage: 1.4 MB

Pandas kütüphanesinin DataFrame metodlarını kullanarak veri setimizi

Veri setinin genel dağılımını anlamak için her bir sayısal sütunun (feature ve target dahil) temel istatistiklerini hesaplıyoruz. Bu adımda ortalama (mean), medyan (median), standart sapma (std) ile minimum ve maksimum değerleri kontrol ederek, veri setinde potansiyel hatalı girişler veya anormallikler (outlier) olup olmadığını araştırıyoruz.

In [4]:
# Sütunların temel istatistiksel dağılımlarını hesaplıyoruz
# .round(2) ile virgülden sonra 2 basamak göstererek okunabilirliği artırıyoruz
display(df.describe().round(2))

,rpm_variation,harsh_braking_count,idling_time,fuel_consumption,acceleration_smoothness,eco_score
count,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
mean,1807.95,2.73,11.28,8.05,0.67,47.49
std,679.42,1.67,5.29,1.51,0.16,19.46
min,500.00,0.00,0.00,3.50,0.03,0.00
25%,1325.00,2.00,7.60,7.03,0.56,34.60
50%,1801.00,3.00,11.20,8.04,0.67,48.40
75%,2272.00,4.00,14.90,9.05,0.78,61.30
max,4935.00,14.00,32.50,14.43,1.00,100.00

# **1.Gün çıktıları :**
### **Dataset kaç satırdan oluşuyor? :**

30.000 Satır ham veriden oluşuyor

### **Kaç kolon bulunuyor? :**

6 Adet kolon bulunuyor

### **Kolonların veri tipleri nedir? :**

 0   rpm_variation              int64  
 1   harsh_braking_count        int64  
 2   idling_time                float64                                        
 3   fuel_consumption           float64                                         
 4   acceleration_smoothness    float64                                        
 5   eco_score                  float64

### **Target değişken hangisidir?**

fuel_consumption kolonu bizim çıktı yani target değişkenlerimizdir,

### **Feature değişkenleri hangileridir?**

rpm_variation ,harsh_braking_count, idling_time, acceleration_smoothness,

eco_score bunlar ise bizim girdi yani features değişkenlerimizdir.